### ISSUE TITLE
Add Logic to Display Author Profile

### ISSUE THREAD

**Issue by nevilkandathil** [Peer2Pressure/Peer2Pressure#60]
**Description**
Add Logic to Display Author Profile

**Comment by jteengfo** [comment]
Added name (will be changed to display name) perhaps will still keep full name as a secondary heading, github profile, as well as a placeholder image (currently commented in the code). Data is currently from a random api but is now able to grab data from apis using useFetch.js

![Image](https://user-images.githubusercontent.com/57475615/221698263-db47107d-1dee-40b9-a172-240f073c2faa.png)
